databases:
  - name: gourmet-experiences
    databaseName: gourmet_experiences
    user: gourmet_experiences_user

services:
  - type: web
    name: Gourmet Experiences
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gourmet-experiences
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
